/* Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved. */
/* SPDX-License-Identifier: Apache-2.0 */

/**
 * @file stringBuilderUInt32Hex_harness.c
 * @brief Implements the proof harness for stringBuilderUInt32Hex function.
 */
/* Include files required for mqtt interface. */
#include "ota_mqtt_private.h"

/* Maximum number of output digits of an unsigned long value. */
#define U32_MAX_LEN    10U

/* Declaration of the mangled name function generated by CBMC for static functions. */
size_t __CPROVER_file_local_ota_mqtt_c_stringBuilderUInt32Hex( char * pBuffer,
                                                               size_t bufferSizeBytes,
                                                               uint32_t value );

void stringBuilderUInt32Hex_harness()
{
    char * pBuffer;
    size_t bufferSizebytes;
    uint32_t value;

    /* The bufferSizebytes is the size of the pBuffer. The pBuffer is statically initialized with
     * a size of U32_MAX_LEN + 1 in all the functions which call stringBuilderUInt32Decimal. Hence,
     * the size can never be below that. */
    __CPROVER_assume( bufferSizebytes > U32_MAX_LEN );

    pBuffer = ( char * ) malloc( bufferSizebytes * sizeof( char ) );

    /* pBuffer is always initialized statically before passing it to the function. Hence,
     * it can never be NULL. */
    __CPROVER_assume( pBuffer != NULL );

    ( void ) __CPROVER_file_local_ota_mqtt_c_stringBuilderUInt32Hex( pBuffer, bufferSizebytes, value );

    free( pBuffer );
}
