blank_issues_enabled: false
contact_links:
  - name: FreeRTOS Community Support Forum
    url: https://forums.freertos.org/
    about: Please ask and answer questions about AWS IoT Over-the-air Update Library here.
