blank_issues_enabled: false
contact_links:
  - name: FreeRTOS Community Support Forum
    url: https://forums.freertos.org/
    about: Please ask and answer questions about IoT Reference Integration on NXP here.
