/* Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved. */
/* SPDX-License-Identifier: Apache-2.0 */

/**
 * @file preprocessBase64Index_harness.c
 * @brief Implements the proof harness for preprocessBase64Index function.
 */
/* Include headers for base64 decoding. */
#include "ota_base64_private.h"

/* Inclusive upper bound for the range of valid Base64 index values. */
#define NON_BASE64_INDEX    67U

/* Declaration of the mangled name function generated by CBMC for static functions. */
Base64Status_t __CPROVER_file_local_ota_base64_c_preprocessBase64Index( uint8_t base64Index,
                                                                        int64_t * pNumPadding,
                                                                        int64_t * pNumWhitespace );

void preprocessBase64Index_harness()
{
    uint8_t base64Index;
    int64_t * pNumPadding;
    int64_t * pNumWhitespace;
    int64_t numPadding;
    int64_t numWhitespace;

    pNumPadding = &numPadding;
    pNumWhitespace = &numWhitespace;

    /* base64Index cannot exceed the NON_BASE64_INDEX which is
     * enforced in ota_base64.c. */
    __CPROVER_assume( base64Index <= NON_BASE64_INDEX );

    /* The numPadding is calculated to be less than max value of int64_t. */
    __CPROVER_assume( numPadding < INT64_MAX );

    /* The numWhitespace is calculated to be less than the max value of int64_t. */
    __CPROVER_assume( numWhitespace < INT64_MAX );

    ( void ) __CPROVER_file_local_ota_base64_c_preprocessBase64Index( base64Index, pNumPadding, pNumWhitespace );
}
